platform :ios, '7.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'AYPageControl', '~> 0.0.2'
pod 'SDAutoLayout', '~> 2.0.0'
pod 'FMDB'
pod 'XHToast'
pod 'IQKeyboardManager'
pod 'BeeCloud/Alipay'
pod 'XHLaunchAd'
pod 'FDFullscreenPopGesture'
